/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;


/**
 *
 * @author Camilo
 */
public class interfaz extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
    public interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
     public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icono.jpg"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFielduUsua = new javax.swing.JTextField();
        jButton2ING = new javax.swing.JButton();
        jButtonReg = new javax.swing.JButton();
        jLabelTitu = new javax.swing.JLabel();
        jLabel1fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("IDENTIFICACIÓN :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        jTextFielduUsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielduUsuaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFielduUsua, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 210, 20));

        jButton2ING.setBackground(new java.awt.Color(51, 255, 51));
        jButton2ING.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2ING.setText("INGRESAR");
        jButton2ING.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2INGActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2ING, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 150, 30));

        jButtonReg.setBackground(new java.awt.Color(0, 153, 153));
        jButtonReg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonReg.setText("AUN NO ESTAS REGISTRADO..?");
        jButtonReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 250, 30));

        jLabelTitu.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        jLabelTitu.setForeground(new java.awt.Color(0, 204, 204));
        jLabelTitu.setText("SIMULACION DE SISTEMAS DE CAJEROS AUTOMATICOS");
        getContentPane().add(jLabelTitu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 660, -1));

        jLabel1fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Camilo\\Desktop\\textures\\zelda-the-legend-of-zelda-triforce-minimalism-hd-wallpaper-preview.jpg")); // NOI18N
        getContentPane().add(jLabel1fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFielduUsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielduUsuaActionPerformed
  
    }//GEN-LAST:event_jTextFielduUsuaActionPerformed

    private void jButtonRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegActionPerformed
        Registrar rg = new Registrar();
         
        rg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonRegActionPerformed

    private void jButton2INGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2INGActionPerformed
        ArrayList<Usuario1> List=new ArrayList<>(); 
      
        if (List.size()==0) {
            JOptionPane.showMessageDialog(null,"Ningun Usuario A sido Registrado");
        }else
        {
            String textousuario=jTextFielduUsua.getText();
        for (int i = 0; i < List.size(); i++) {
            if (textousuario.equalsIgnoreCase(List.get(i).getID())){
                 JOptionPane.showMessageDialog(this, "Persona registrada");
          } else {
        JOptionPane.showMessageDialog(this, "No estas registrado");
            }
        }
        }
    }//GEN-LAST:event_jButton2INGActionPerformed
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //ArrayList<Cuenta> List =new ArrayList<>();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2ING;
    private javax.swing.JButton jButtonReg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1fondo;
    private javax.swing.JLabel jLabelTitu;
    private javax.swing.JTextField jTextFielduUsua;
    // End of variables declaration//GEN-END:variables
}
