/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Camilo
 */
public class Registrar extends javax.swing.JFrame {

    /**
     * Creates new form Registrar
     */
    public Registrar() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

     public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icono.jpg"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        nombre = new javax.swing.JLabel();
        APELLIDO = new javax.swing.JLabel();
        CORREO = new javax.swing.JLabel();
        TIPOid = new javax.swing.JLabel();
        DOCUMENTO = new javax.swing.JLabel();
        DEPAR = new javax.swing.JLabel();
        MUN = new javax.swing.JLabel();
        TELEFONO = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        JTexCorreo = new javax.swing.JTextField();
        JTextNombre1 = new javax.swing.JTextField();
        JTextApe = new javax.swing.JTextField();
        JTexTel = new javax.swing.JTextField();
        JTexID = new javax.swing.JTextField();
        JTextTipo = new javax.swing.JTextField();
        JTextDepar = new javax.swing.JTextField();
        JTextMun = new javax.swing.JTextField();
        JTextFechaNam = new javax.swing.JTextField();
        JTextGen = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        Salida = new javax.swing.JLabel();
        jLabelfondo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        nombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nombre.setText("NOMBRE");
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        APELLIDO.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        APELLIDO.setText("APELLIDO");
        getContentPane().add(APELLIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, -1));

        CORREO.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CORREO.setText("CORREO");
        getContentPane().add(CORREO, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, -1, -1));

        TIPOid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TIPOid.setText("TIPO DE ID");
        getContentPane().add(TIPOid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        DOCUMENTO.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DOCUMENTO.setText("NUMERO DE DOCUMENTO");
        getContentPane().add(DOCUMENTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, -1));

        DEPAR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DEPAR.setText("DEPARTAMENTO");
        getContentPane().add(DEPAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        MUN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MUN.setText("MUNICIPIO");
        getContentPane().add(MUN, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, -1));

        TELEFONO.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TELEFONO.setText("TELEFONO");
        getContentPane().add(TELEFONO, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("GENERO");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("FECHA DE NACIMIENTO");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, -1, -1));

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("         NUEVOS REGISTROS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 630, 60));
        getContentPane().add(JTexCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 210, 30));

        JTextNombre1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTextNombre1MouseClicked(evt);
            }
        });
        JTextNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextNombre1ActionPerformed(evt);
            }
        });
        getContentPane().add(JTextNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 210, 30));
        getContentPane().add(JTextApe, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 210, 30));
        getContentPane().add(JTexTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 210, 30));
        getContentPane().add(JTexID, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 210, 30));
        getContentPane().add(JTextTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 210, 30));
        getContentPane().add(JTextDepar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 210, 30));
        getContentPane().add(JTextMun, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 210, 30));
        getContentPane().add(JTextFechaNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 210, 30));
        getContentPane().add(JTextGen, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 210, 30));

        jButton2.setBackground(new java.awt.Color(51, 255, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 102));
        jButton2.setText("REGISTRARME");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 170, 40));

        Salida.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Salida.setForeground(new java.awt.Color(0, 153, 153));
        getContentPane().add(Salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, 200, 60));

        jLabelfondo2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Camilo\\Desktop\\Imagenes Interfaz\\thumb-1920-1310233.jpg")); // NOI18N
        getContentPane().add(jLabelfondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 509));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      interfaz rg = new interfaz();
         
        rg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JTextNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextNombre1ActionPerformed
           
    }//GEN-LAST:event_JTextNombre1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked

        Salida.setText("USUARIO REGISTRADO");   
    }//GEN-LAST:event_jButton2MouseClicked

    private void JTextNombre1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTextNombre1MouseClicked
        ArrayList<Usuario1> List=new ArrayList<>(); 
        String nombre;
        
       nombre=JOptionPane.showInputDialog("la suma es : ");
       
            List.add(new Usuario1());  
        
       
      
                  
                 
    }//GEN-LAST:event_JTextNombre1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel APELLIDO;
    private javax.swing.JLabel CORREO;
    private javax.swing.JLabel DEPAR;
    private javax.swing.JLabel DOCUMENTO;
    private javax.swing.JTextField JTexCorreo;
    private javax.swing.JTextField JTexID;
    private javax.swing.JTextField JTexTel;
    private javax.swing.JTextField JTextApe;
    private javax.swing.JTextField JTextDepar;
    private javax.swing.JTextField JTextFechaNam;
    private javax.swing.JTextField JTextGen;
    private javax.swing.JTextField JTextMun;
    private javax.swing.JTextField JTextNombre1;
    private javax.swing.JTextField JTextTipo;
    private javax.swing.JLabel MUN;
    private javax.swing.JLabel Salida;
    private javax.swing.JLabel TELEFONO;
    private javax.swing.JLabel TIPOid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelfondo2;
    private javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables
}
